# Generated by Django 6.0.2 on 2026-02-26 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.IntegerField(unique=True)),
                (
                    "card_number",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                ("holder_name", models.CharField(max_length=100)),
                ("pin", models.CharField(max_length=6)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "qr_token",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Savings Account"),
                            ("CURRENT", "Current Account"),
                        ],
                        max_length=10,
                    ),
                ),
                ("failed_attempts", models.IntegerField(default=0)),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAW", "Withdraw"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("remark", models.CharField(blank=True, max_length=100, null=True)),
                ("is_fraud", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="main.account",
                    ),
                ),
            ],
        ),
    ]
