# Generated by Django 6.0.2 on 2026-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="block_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="pin",
            field=models.CharField(max_length=4),
        ),
    ]
