# Generated by Django 6.0.2 on 2026-02-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_account_blocked_until_account_failed_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
