# Generated by Django 6.0.2 on 2026-03-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_account_block_count_alter_account_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_permanent_block",
            field=models.BooleanField(default=False),
        ),
    ]
