# Generated by Django 6.0.2 on 2026-02-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_account_card_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="qr_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
