# Generated by Django 6.0.2 on 2026-03-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_account_is_permanent_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
