# Generated by Django 6.0.2 on 2026-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_account_qr_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
