# Generated by Django 6.0.2 on 2026-03-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_account_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Completed"),
                    ("PENDING_OTP", "Pending OTP"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="COMPLETED",
                max_length=20,
            ),
        ),
    ]
