# Generated by Django 6.0.2 on 2026-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_account_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_fraud",
            field=models.BooleanField(default=False),
        ),
    ]
